name: go-docker-actions-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Posgresql DB for testing
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: dzovi
          POSTGRES_PASSWORD: azerty
          POSTGRES_DB: assignmentDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build the Go+Postgres App using Docker
        run: go test ./...
